### ISSUE TITLE
Set up airplane database

### ISSUE THREAD

**Issue by bwoodbury3** [ndharasz/onthefly-android#41]
## Story/Task Details
- [x] A user can choose a plane from the database
- [ ] The plane from the database is reflected in the drag/drop menu (correct number of seats, correct seat orientation)
- [ ] A flight calculation can be calculated given the database information

## Acceptance Scenarios
- Given: A user wants to create a flight
- When: he/she selects a plane from the drop-down menu
- Then: he/she is able to configure the flight and be given a correct W&B report for that plane.

**Comment by ndharasz** [comment]
This is mainly a database issue handled outside of normal app development.
