### ISSUE TITLE
Stretch-feature: Offline data storage

### ISSUE THREAD

**Issue by ndharasz** [ndharasz/onthefly-android#45]
## Story/Task Details
- [ ] Detect when the user is offline.
- [ ] Save any/all new data generated by user (flights, passengers, reports).
- [ ] Send to database next time user opens app and is online.

## Acceptance Scenarios
- Given: Data should be transmitted
- When: the user is offline
- Then: save the data and transmit later.

**Comment by shiggins8** [comment]
Needs to be researched, but I think Firebase may have tools/API calls that help with this.
