### ISSUE TITLE
Return to List from Edit Screen

### ISSUE THREAD

**Issue by bwoodbury3** [ndharasz/onthefly-android#55]
## Story/Task Details
- [ ] As a user, I want to be able to return to the flight list without clicking through the CreateFlight screen

## Acceptance Scenarios
- Given: A user has created a flight and hit "submit"
- When: He/she needs to return to the flight list
- Then: He/she should click a back button to return to the list of flights

**Comment by ndharasz** [comment]
This functionality is already available using Android's native back-button.
